apiVersion: v1
kind: Service
metadata:
  name: carepro-web
spec:
  type: NodePort
  selector:
    app: carepro-web
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30001  # Note: NodePort must be in the range 30000-32767 on most Kubernetes setups
